#!/usr/bin/env python3
"""
Run SDCN_DLAA on a labeled conceptual dataset directory and emit a small summary JSON.

Expected files in `--data_dir` (generated by tools/generate_conceptual_data.py):
- node_features.npy
- labels.npy
- binary_adj.npz
- edge_attr.npy
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np
import scipy.sparse as sp
import torch

# Ensure repo root is importable when running from an arbitrary cwd.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from evaluation import eva  # noqa: E402
from sdcn_dlaa_NEW import train_sdcn_dlaa_custom  # noqa: E402


class NumpyDataset:
    def __init__(self, x: np.ndarray, y: np.ndarray):
        self.x = x
        self.y = y
        self.num_nodes, self.num_features = x.shape


def sparse_mx_to_torch_sparse_tensor(sparse_mx: sp.spmatrix) -> torch.Tensor:
    sparse_mx = sparse_mx.tocoo().astype(np.float32)
    indices = torch.from_numpy(np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
    values = torch.from_numpy(sparse_mx.data)
    shape = torch.Size(sparse_mx.shape)
    return torch.sparse_coo_tensor(indices, values, shape)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_dir", type=str, required=True)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--n_clusters", type=int, default=None)
    parser.add_argument("--n_z", type=int, default=10)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--heads", type=int, default=1)
    parser.add_argument("--edge_dim", type=int, default=10)
    parser.add_argument("--max_edges_per_node", type=int, default=10)
    parser.add_argument("--cpu", action="store_true")
    parser.add_argument("--summary_json", type=str, default="summary.json")
    args = parser.parse_args()

    x = np.load(os.path.join(args.data_dir, "node_features.npy")).astype(np.float32)
    y = np.load(os.path.join(args.data_dir, "labels.npy")).astype(np.int64)
    edge_attr_np = np.load(os.path.join(args.data_dir, "edge_attr.npy")).astype(np.float32)
    adj_sp = sp.load_npz(os.path.join(args.data_dir, "binary_adj.npz"))

    if args.n_clusters is None:
        args.n_clusters = int(np.unique(y).size)

    dataset = NumpyDataset(x=x, y=y)

    use_cuda = torch.cuda.is_available() and not args.cpu
    args.cuda = use_cuda
    args.device = torch.device("cuda" if use_cuda else "cpu")

    adj = sparse_mx_to_torch_sparse_tensor(adj_sp).to(args.device)
    edge_attr = torch.from_numpy(edge_attr_np).float().to(args.device)
    args.n_input = dataset.num_features

    model, results_df, clusters = train_sdcn_dlaa_custom(dataset, adj, args, edge_attr)

    final_acc, final_f1, final_nmi, final_ari = eva(dataset.y, clusters, epoch="final")
    unique, counts = np.unique(clusters, return_counts=True)
    cluster_distribution = {int(k): int(v) for k, v in zip(unique, counts)}

    summary = {
        "data_dir": os.path.abspath(args.data_dir),
        "n_clusters": int(args.n_clusters),
        "n_nodes": int(dataset.num_nodes),
        "metrics": {
            "acc": float(final_acc),
            "f1": float(final_f1),
            "nmi": float(final_nmi),
            "ari": float(final_ari),
        },
        "cluster_distribution": cluster_distribution,
        "cuda": bool(use_cuda),
        "torch_device": str(args.device),
    }

    with open(args.summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print(f"Wrote summary to: {os.path.abspath(args.summary_json)}")


if __name__ == "__main__":
    main()

